modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="code_lyoko"
version="1.0.0"
displayName="code lyoko"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="user2, MCreator"

[[dependencies.code_lyoko]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




